insert into public.legends (id, name, set_name) values
  ('ahri-nine-tailed-fox', 'Ahri, Nine-Tailed Fox', 'Origins'),
  ('annie-dark-child', 'Annie, Dark Child', 'Origins'),
  ('azir-emperor-of-the-sands', 'Azir, Emperor of the Sands', 'Spiritforged'),
  ('darius-hand-of-noxus', 'Darius, Hand of Noxus', 'Origins'),
  ('diana-scorn-of-the-moon', 'Diana, Scorn of the Moon', 'Unleashed'),
  ('draven-glorious-executioner', 'Draven, Glorious Executioner', 'Spiritforged'),
  ('ezreal-prodigal-explorer', 'Ezreal, Prodigal Explorer', 'Spiritforged'),
  ('fiora-grand-duelist', 'Fiora, Grand Duelist', 'Spiritforged'),
  ('garen-might-of-demacia', 'Garen, Might of Demacia', 'Origins'),
  ('irelia-blade-dancer', 'Irelia, Blade Dancer', 'Spiritforged'),
  ('ivern-green-father', 'Ivern, Green Father', 'Spiritforged'),
  ('jax-grandmaster-at-arms', 'Jax, Grandmaster at Arms', 'Spiritforged'),
  ('jhin-virtuoso', 'Jhin, Virtuoso', 'Spiritforged'),
  ('jinx-loose-cannon', 'Jinx, Loose Cannon', 'Origins'),
  ('kaisa-daughter-of-the-void', 'Kai''Sa, Daughter of the Void', 'Origins'),
  ('khazix-voidreaver', 'Kha''Zix, Voidreaver', 'Unleashed'),
  ('leblanc-deceiver', 'LeBlanc, Deceiver', 'Spiritforged'),
  ('lee-sin-blind-monk', 'Lee Sin, Blind Monk', 'Origins'),
  ('leona-radiant-dawn', 'Leona, Radiant Dawn', 'Origins'),
  ('lillia-bashful-bloom', 'Lillia, Bashful Bloom', 'Unleashed'),
  ('lucian-purifier', 'Lucian, Purifier', 'Unleashed'),
  ('lux-lady-of-luminosity', 'Lux, Lady of Luminosity', 'Origins'),
  ('master-yi-wuju-bladesman', 'Master Yi, Wuju Bladesman', 'Unleashed'),
  ('master-yi-wuju-master', 'Master Yi, Wuju Master', 'Origins'),
  ('miss-fortune-bounty-hunter', 'Miss Fortune, Bounty Hunter', 'Origins'),
  ('ornn-fire-below-the-mountain', 'Ornn, Fire Below the Mountain', 'Spiritforged'),
  ('poppy-keeper-of-the-hammer', 'Poppy, Keeper of the Hammer', 'Spiritforged'),
  ('pyke-bloodharbor-ripper', 'Pyke, Bloodharbor Ripper', 'Unleashed'),
  ('reksai-void-burrower', 'Rek''Sai, Void Burrower', 'Unleashed'),
  ('renata-glasc-chem-baroness', 'Renata Glasc, Chem-Baroness', 'Unleashed'),
  ('rengar-pridestalker', 'Rengar, Pridestalker', 'Unleashed'),
  ('rumble-mechanized-menace', 'Rumble, Mechanized Menace', 'Spiritforged'),
  ('sett-the-boss', 'Sett, The Boss', 'Origins'),
  ('sivir-battle-mistress', 'Sivir, Battle Mistress', 'Unleashed'),
  ('teemo-swift-scout', 'Teemo, Swift Scout', 'Origins'),
  ('vex-gloomist', 'Vex, Gloomist', 'Unleashed'),
  ('vi-piltover-enforcer', 'Vi, Piltover Enforcer', 'Unleashed'),
  ('viktor-herald-of-the-arcane', 'Viktor, Herald of the Arcane', 'Origins'),
  ('volibear-relentless-storm', 'Volibear, Relentless Storm', 'Origins'),
  ('yasuo-unforgiven', 'Yasuo, Unforgiven', 'Origins')
on conflict (id) do update set
  name = excluded.name,
  set_name = excluded.set_name;
