insert into public.legends (id, name, set_name) values
  ('ahri-nine-tailed-fox', 'Ahri, Nine-Tailed Fox', 'Origins'),
  ('annie-dark-child', 'Annie, Dark Child', 'Origins'),
  ('azir-emperor-of-the-sands', 'Azir, Emperor of the Sands', 'Spiritforged'),
  ('darius-hand-of-noxus', 'Darius, Hand of Noxus', 'Origins'),
  ('diana-scorn-of-the-moon', 'Diana, Scorn of the Moon', 'Unleashed'),
  ('draven-glorious-executioner', 'Draven, Glorious Executioner', 'Spiritforged'),
  ('ezreal-prodigal-explorer', 'Ezreal, Prodigal Explorer', 'Spiritforged'),
  ('fiora-grand-duelist', 'Fiora, Grand Duelist', 'Spiritforged'),
  ('garen-might-of-demacia', 'Garen, Might of Demacia', 'Origins'),
  ('irelia-blade-dancer', 'Irelia, Blade Dancer', 'Spiritforged'),
  ('ivern-green-father', 'Ivern, Green Father', 'Spiritforged'),
  ('jax-grandmaster-at-arms', 'Jax, Grandmaster at Arms', 'Spiritforged'),
  ('jhin-virtuoso', 'Jhin, Virtuoso', 'Spiritforged'),
  ('jinx-loose-cannon', 'Jinx, Loose Cannon', 'Origins'),
  ('kaisa-daughter-of-the-void', 'Kai''Sa, Daughter of the Void', 'Origins'),
  ('khazix-voidreaver', 'Kha''Zix, Voidreaver', 'Unleashed'),
  ('leblanc-deceiver', 'LeBlanc, Deceiver', 'Spiritforged'),
  ('lee-sin-blind-monk', 'Lee Sin, Blind Monk', 'Origins'),
  ('leona-radiant-dawn', 'Leona, Radiant Dawn', 'Origins'),
  ('lillia-bashful-bloom', 'Lillia, Bashful Bloom', 'Unleashed'),
  ('lucian-purifier', 'Lucian, Purifier', 'Unleashed'),
  ('lux-lady-of-luminosity', 'Lux, Lady of Luminosity', 'Origins'),
  ('master-yi-wuju-bladesman', 'Master Yi, Wuju Bladesman', 'Unleashed'),
  ('master-yi-wuju-master', 'Master Yi, Wuju Master', 'Origins'),
  ('miss-fortune-bounty-hunter', 'Miss Fortune, Bounty Hunter', 'Origins'),
  ('ornn-fire-below-the-mountain', 'Ornn, Fire Below the Mountain', 'Spiritforged'),
  ('poppy-keeper-of-the-hammer', 'Poppy, Keeper of the Hammer', 'Spiritforged'),
  ('pyke-bloodharbor-ripper', 'Pyke, Bloodharbor Ripper', 'Unleashed'),
  ('reksai-void-burrower', 'Rek''Sai, Void Burrower', 'Unleashed'),
  ('renata-glasc-chem-baroness', 'Renata Glasc, Chem-Baroness', 'Unleashed'),
  ('rengar-pridestalker', 'Rengar, Pridestalker', 'Unleashed'),
  ('rumble-mechanized-menace', 'Rumble, Mechanized Menace', 'Spiritforged'),
  ('sett-the-boss', 'Sett, The Boss', 'Origins'),
  ('sivir-battle-mistress', 'Sivir, Battle Mistress', 'Unleashed'),
  ('teemo-swift-scout', 'Teemo, Swift Scout', 'Origins'),
  ('vex-gloomist', 'Vex, Gloomist', 'Unleashed'),
  ('vi-piltover-enforcer', 'Vi, Piltover Enforcer', 'Unleashed'),
  ('viktor-herald-of-the-arcane', 'Viktor, Herald of the Arcane', 'Origins'),
  ('volibear-relentless-storm', 'Volibear, Relentless Storm', 'Origins'),
  ('yasuo-unforgiven', 'Yasuo, Unforgiven', 'Origins')
on conflict (id) do update set
  name = excluded.name,
  set_name = excluded.set_name;

with legacy_legends (old_id, new_id) as (
  values
    ('ahri', 'ahri-nine-tailed-fox'),
    ('annie', 'annie-dark-child'),
    ('azir', 'azir-emperor-of-the-sands'),
    ('darius', 'darius-hand-of-noxus'),
    ('diana', 'diana-scorn-of-the-moon'),
    ('draven', 'draven-glorious-executioner'),
    ('ezreal', 'ezreal-prodigal-explorer'),
    ('fiora', 'fiora-grand-duelist'),
    ('garen', 'garen-might-of-demacia'),
    ('irelia', 'irelia-blade-dancer'),
    ('ivern', 'ivern-green-father'),
    ('jax', 'jax-grandmaster-at-arms'),
    ('jhin', 'jhin-virtuoso'),
    ('jinx', 'jinx-loose-cannon'),
    ('kaisa', 'kaisa-daughter-of-the-void'),
    ('khazix', 'khazix-voidreaver'),
    ('leblanc', 'leblanc-deceiver'),
    ('lee-sin', 'lee-sin-blind-monk'),
    ('leona', 'leona-radiant-dawn'),
    ('lillia', 'lillia-bashful-bloom'),
    ('lucian', 'lucian-purifier'),
    ('lux', 'lux-lady-of-luminosity'),
    ('master-yi', 'master-yi-wuju-master'),
    ('miss-fortune', 'miss-fortune-bounty-hunter'),
    ('ornn', 'ornn-fire-below-the-mountain'),
    ('poppy', 'poppy-keeper-of-the-hammer'),
    ('pyke', 'pyke-bloodharbor-ripper'),
    ('rek-sai', 'reksai-void-burrower'),
    ('renata-glasc', 'renata-glasc-chem-baroness'),
    ('rengar', 'rengar-pridestalker'),
    ('rumble', 'rumble-mechanized-menace'),
    ('sett', 'sett-the-boss'),
    ('sivir', 'sivir-battle-mistress'),
    ('teemo', 'teemo-swift-scout'),
    ('vex', 'vex-gloomist'),
    ('vi', 'vi-piltover-enforcer'),
    ('viktor', 'viktor-herald-of-the-arcane'),
    ('volibear', 'volibear-relentless-storm'),
    ('yasuo', 'yasuo-unforgiven')
)
update public.matches
set player_legend_id = legacy_legends.new_id
from legacy_legends
where matches.player_legend_id = legacy_legends.old_id;

with legacy_legends (old_id, new_id) as (
  values
    ('ahri', 'ahri-nine-tailed-fox'),
    ('annie', 'annie-dark-child'),
    ('azir', 'azir-emperor-of-the-sands'),
    ('darius', 'darius-hand-of-noxus'),
    ('diana', 'diana-scorn-of-the-moon'),
    ('draven', 'draven-glorious-executioner'),
    ('ezreal', 'ezreal-prodigal-explorer'),
    ('fiora', 'fiora-grand-duelist'),
    ('garen', 'garen-might-of-demacia'),
    ('irelia', 'irelia-blade-dancer'),
    ('ivern', 'ivern-green-father'),
    ('jax', 'jax-grandmaster-at-arms'),
    ('jhin', 'jhin-virtuoso'),
    ('jinx', 'jinx-loose-cannon'),
    ('kaisa', 'kaisa-daughter-of-the-void'),
    ('khazix', 'khazix-voidreaver'),
    ('leblanc', 'leblanc-deceiver'),
    ('lee-sin', 'lee-sin-blind-monk'),
    ('leona', 'leona-radiant-dawn'),
    ('lillia', 'lillia-bashful-bloom'),
    ('lucian', 'lucian-purifier'),
    ('lux', 'lux-lady-of-luminosity'),
    ('master-yi', 'master-yi-wuju-master'),
    ('miss-fortune', 'miss-fortune-bounty-hunter'),
    ('ornn', 'ornn-fire-below-the-mountain'),
    ('poppy', 'poppy-keeper-of-the-hammer'),
    ('pyke', 'pyke-bloodharbor-ripper'),
    ('rek-sai', 'reksai-void-burrower'),
    ('renata-glasc', 'renata-glasc-chem-baroness'),
    ('rengar', 'rengar-pridestalker'),
    ('rumble', 'rumble-mechanized-menace'),
    ('sett', 'sett-the-boss'),
    ('sivir', 'sivir-battle-mistress'),
    ('teemo', 'teemo-swift-scout'),
    ('vex', 'vex-gloomist'),
    ('vi', 'vi-piltover-enforcer'),
    ('viktor', 'viktor-herald-of-the-arcane'),
    ('volibear', 'volibear-relentless-storm'),
    ('yasuo', 'yasuo-unforgiven')
)
update public.matches
set opponent_legend_id = legacy_legends.new_id
from legacy_legends
where matches.opponent_legend_id = legacy_legends.old_id;

delete from public.legends
where id in (
  'ahri',
  'annie',
  'azir',
  'darius',
  'diana',
  'draven',
  'ezreal',
  'fiora',
  'garen',
  'irelia',
  'ivern',
  'jax',
  'jhin',
  'jinx',
  'kaisa',
  'khazix',
  'leblanc',
  'lee-sin',
  'leona',
  'lillia',
  'lucian',
  'lux',
  'master-yi',
  'miss-fortune',
  'ornn',
  'poppy',
  'pyke',
  'rek-sai',
  'renata-glasc',
  'rengar',
  'rumble',
  'sett',
  'sivir',
  'teemo',
  'vex',
  'vi',
  'viktor',
  'volibear',
  'yasuo'
);
